### ISSUE TITLE
Intended use for new genesis_simple_hooks_hooks filter?

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-hooks#12]
I was excited to see the new `genesis_simple_hooks_hooks` filter, but for me it does not allow users to add or remove hooks in the default list.

Removal of existing hooks attempt (added to child theme `functions.php`):

~~~php
add_filter( 'genesis_simple_hooks_hooks', 'sp_remove_hooks' );
function sp_remove_hooks( $hooks ) {
	return array_diff( $hooks, array( 'wp_head', 'wp_footer' ) );
}
~~~

This removes the `wp_head` and `wp_footer` from the `$hooks` array, but I still see them in the admin area.

Addition of new hooks attempt:

~~~php
add_filter( 'genesis_simple_hooks_hooks', 'sp_more_hooks' );
function sp_more_hooks( $hooks ) {
	return array_merge( $hooks, array( 'my_new_hook', 'my_new_hook2' ) );
}
~~~

I see the two new hooks in the `$hooks` array, but not in the admin area. (Perhaps because `generate_form_markup_from_hooks()` is never called on those new hooks?)

Perhaps I've misinterpreted the use case here, but from what I can see filtering has no effect.

**Comment by nathanrice** [comment]
028b12b

OK, so yeah, this filter didn't really do anything other than modify the default settings that get saved on registration and reset.

So, I added a check to the form markup output. It won't let you ADD hooks, since that's not really practical with so many hook groups, and given the fact that this is GENESIS Simple Hooks (adding your own seems silly). But you can remove some, if that is something you want to do.

Your method above should work.

However, this actually made it so we ended up with empty metaboxes if you removed all the hooks from a hook group.

So, I'm going to remove the filter for now. We can revisit it later, but I don't want a new filter in place that is going to confuse people.

**Comment by nathanrice** [comment]
7ad9587
